logging:  
  config: classpath:logback.xml
  path: /home/yt00701/Documents/log/shareSessionTest
server:  
  port: 8080
  session:
    timeout: 60
  
spring:  
    redis:  
       database: 0
       host: 127.0.0.1
       port: 6379
       password:
       timeout: 0
       pool:
           max-active: 8
           max-wait: -1
           max-idle: 8
           min-idle: 0
